# ************************************************************
# Sequel Pro SQL dump
# Version 4499
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: localhost (MySQL 5.5.42)
# Database: npomusic
# Generation Time: 2015-12-15 17:21:33 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table bekendebners
# ------------------------------------------------------------

DROP TABLE IF EXISTS `bekendebners`;

CREATE TABLE `bekendebners` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bnervoornaam` varchar(255) NOT NULL,
  `bnerachternaam` varchar(255) NOT NULL,
  `bnerinfo` varchar(255) NOT NULL,
  `bnerimage` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table topsongs
# ------------------------------------------------------------

DROP TABLE IF EXISTS `topsongs`;

CREATE TABLE `topsongs` (
  `song_id` int(11) NOT NULL AUTO_INCREMENT,
  `song_nr` int(11) NOT NULL,
  `song_title` varchar(255) NOT NULL,
  `song_singer` varchar(255) NOT NULL,
  `song_info` varchar(255) NOT NULL,
  `song_embed` varchar(255) NOT NULL,
  `song_embed_klein` varchar(255) NOT NULL,
  `show_at` date NOT NULL,
  PRIMARY KEY (`song_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `topsongs` WRITE;
/*!40000 ALTER TABLE `topsongs` DISABLE KEYS */;

INSERT INTO `topsongs` (`song_id`, `song_nr`, `song_title`, `song_singer`, `song_info`, `song_embed`, `song_embed_klein`, `show_at`)
VALUES
	(1,100,'Dingue dingue dingue','Christophe Maé','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Rwv1djaV6Fc\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Rwv1djaV6Fc\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-02'),
	(2,99,'Du côté de chez Swann','Dave','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/SzvC1OWCBL4\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/SzvC1OWCBL4\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-02'),
	(3,98,'Une fille aux jeux clairs','Michel Sardou ','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/dcBPaySVtBw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/dcBPaySVtBw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-02'),
	(4,97,'Les rois du monde','Cast Roméo & Juliette','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/cQ87IIvXp7s\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/cQ87IIvXp7s\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-02'),
	(5,96,'Ring et ding','Michel Fugain','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/SCG3q7FyUNA\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/SCG3q7FyUNA\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-02'),
	(6,95,'T’en va pas','Elsa','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/TeaKAB-IxOE\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/TeaKAB-IxOE\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-03'),
	(7,94,'Je suis venue te dire que je m’en vais','Jo Lemaire & Flouze','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/NrUCTDkxXLw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/NrUCTDkxXLw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-03'),
	(8,93,'(Je suis un) Soulman','Ben l’Oncle Soul','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/69ptYXvUo7M\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/69ptYXvUo7M\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-03'),
	(9,92,'Non non non','Camélia Jordana','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/JswOaaE9X-I\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/JswOaaE9X-I\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-03'),
	(10,91,'Allons à Lafayette','Captain Gumbo','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/6fDBxgm-F9E\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/6fDBxgm-F9E\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-03'),
	(11,90,'Les filles du bord de mer','Adamo','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/fh5oydvwqZU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/fh5oydvwqZU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-04'),
	(12,89,'Comment te dire adieu','Françoise Hardy','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/mwhX5V1Gn6w\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/mwhX5V1Gn6w\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-04'),
	(13,88,'J’ai vu Paris','Charles Aznavour','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/aXJ20S1aAcU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/aXJ20S1aAcU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-04'),
	(14,87,'J’ai demandé à la lune','Indochine','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/KAOmC5qT02w\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/KAOmC5qT02w\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-04'),
	(15,86,'Sous le ciel de Paris','Edith Piaf','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/uOXzGtlLGgw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/uOXzGtlLGgw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-04'),
	(16,85,'Tu te reconnaitras','Anne-Marie David ','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/zn1svLVprUk\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/zn1svLVprUk\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-05'),
	(17,84,'Mademoiselle chante le blues','Patricia Kaas','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/HOiUkXFsjdU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/HOiUkXFsjdU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-05'),
	(18,83,'Isabelle je t’aime','Les Poppys ','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/o618mlIaR7E\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/o618mlIaR7E\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-05'),
	(19,82,'J’attendrai','Dalida','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/kIX4Zo_r1Qk\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/kIX4Zo_r1Qk\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-05'),
	(20,81,'Le long de la route','Zaz','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/XZaI3kVnoeA\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/XZaI3kVnoeA\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-05'),
	(21,80,'Maldon','Zouk Machine','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/BPdrGOFXzGA\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/BPdrGOFXzGA\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-06'),
	(22,79,'Ma préférence','Julien Clerc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/WsOWxbnpkAw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/WsOWxbnpkAw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-06'),
	(23,78,'Bruxelles','Jacques Brel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/SX-8jLFvHCI\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/SX-8jLFvHCI\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-06'),
	(24,77,'1 2 3','Catherine Ferry','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/G_9xKxwJV8s\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/G_9xKxwJV8s\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-06'),
	(25,76,'Il jouait du piano debout','France Gall','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/mZauenMD52I\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/mZauenMD52I\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-06'),
	(26,75,'Adieu Monsieur le professeur','Hughes Aufray','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/cZPIKXBLk70\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/cZPIKXBLk70\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-07'),
	(27,74,'Brave Margot','Georges Brassens','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/zuxMhzKeozo\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/zuxMhzKeozo\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-07'),
	(28,73,'Amoureux solitaires','Lio','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/6aIgGbO8rQ0\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/6aIgGbO8rQ0\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-07'),
	(29,72,'Inch Allah','Adamo','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/rcefF7d_K2w\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/rcefF7d_K2w\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-07'),
	(30,71,'Quelqu’un m’a dit','Carla Bruni','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/QAlo_1zQDuo\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/QAlo_1zQDuo\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-07'),
	(31,70,'Mon amour','BZN','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/4J7OeTPEe0A\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/4J7OeTPEe0A\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-08'),
	(32,69,'Prendre un enfant','Yves Duteil','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/jcF4UiIx52o\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/jcF4UiIx52o\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-08'),
	(33,68,'Mes emmerdes','Charles Aznavour','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/libXP153AlM\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/libXP153AlM\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-08'),
	(34,67,'J’aime la vie','Sandra Kim','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/SJKFT0VUyf4\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/SJKFT0VUyf4\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-08'),
	(35,66,'La tribu de Dana','Manau','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/MI2-w9q_Lk4\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/MI2-w9q_Lk4\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-08'),
	(36,65,'C’est ma vie','Adamo','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/KjP01gwxNSo\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/KjP01gwxNSo\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-09'),
	(37,64,'Désenchantée','Kate Ryan ','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/tmPws7eXcVk\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/tmPws7eXcVk\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-09'),
	(38,63,'Milord ','Edith Piaf','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/vwe3CzWZ4Bg\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/vwe3CzWZ4Bg\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-09'),
	(39,62,'Le lac majeur','Mort Shuman','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/5vSTf-ZNAxw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/5vSTf-ZNAxw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-09'),
	(40,61,'Quand le soleil dit bonjour aux montagnes','Lucille Starr','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/aChSCXFFPlQ\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/aChSCXFFPlQ\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-09'),
	(41,60,'Si on chantait','Julien Clerc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/DxUKvPYFaxo\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/DxUKvPYFaxo\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-10'),
	(42,59,'Dansez maintenant','Dave','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/zQU3Y-as7ug\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/zQU3Y-as7ug\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-10'),
	(43,58,'Et maintenant','Gilbert Bécaud','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/hmSBAJdie7E\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/hmSBAJdie7E\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-10'),
	(44,57,'Çe n’est rien','Julien Clerc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/ZzQ403SHTPM\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/ZzQ403SHTPM\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-10'),
	(45,56,'La mamma','Charles Aznavour','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/ls8Cn5abrX0\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/ls8Cn5abrX0\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-10'),
	(46,55,'Alors on danse','Stromae','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/VHoT4N43jK8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/VHoT4N43jK8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-11'),
	(47,54,'C’est moi','C. Jérôme','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/3GRaJvvC_5o\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/3GRaJvvC_5o\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-11'),
	(48,53,'La vie en rose','Grace Jones','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/kYkVtz6ozJE\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/kYkVtz6ozJE\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-11'),
	(49,52,'Si j’étais président','Gérard Lenorman','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/s565nXsXTrg\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/s565nXsXTrg\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-11'),
	(50,51,'Marieke','Jacques Brel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/wfGDpzL9H7Y\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/wfGDpzL9H7Y\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-11'),
	(51,50,'L’été Indien','Joe Dassin','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/tQb4eWCAq8c\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/tQb4eWCAq8c\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-12'),
	(52,49,'Tombe la neige','Adamo','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/OQKSU6j1-8U\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/OQKSU6j1-8U\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-12'),
	(53,48,'Chaque fois','Wende','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/8SNh8EQ3ViQ\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/8SNh8EQ3ViQ\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-12'),
	(54,47,'Les feuilles mortes','Yves Montand','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Xo1C6E7jbPw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Xo1C6E7jbPw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-12'),
	(55,46,'La vie en rose','Edith Piaf','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/0feNVUwQA8U\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/0feNVUwQA8U\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-12'),
	(56,45,'Voyage voyage','Desireless','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/6PDmZnG8KsM\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/6PDmZnG8KsM\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-13'),
	(57,44,'Voici les clés','Gérard Lenorman','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/5gYw7VHx4Ok\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/5gYw7VHx4Ok\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-13'),
	(58,43,'Venise','Julien Clerc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/UhQnVyz627c\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/UhQnVyz627c\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-13'),
	(59,42,'Joe le taxi','Vanessa Paradis','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Ulay2FvUEd8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Ulay2FvUEd8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-13'),
	(60,41,'Tu es foutu','In-grid','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/qOGSqC7xds8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/qOGSqC7xds8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-13'),
	(61,40,'Le vent nous portera','Noir Désir','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/NrgcRvBJYBE\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/NrgcRvBJYBE\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-14'),
	(62,39,'Salad tomate oignon','La Caravane Passe','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Lh49fLPhw2I\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Lh49fLPhw2I\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-14'),
	(63,38,'Les Champs-Elysées','Joe Dassin','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/M4C6cqo4EjY\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/M4C6cqo4EjY\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-14'),
	(64,37,'Le métèque','Georges Moustaki','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/MV8fGf-N06A\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/MV8fGf-N06A\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-14'),
	(65,36,'La bohème','Charles Aznavour','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/xzdxyhng1RU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/xzdxyhng1RU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-14'),
	(66,35,'Gigi l’amoroso','Dalida','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Fb63wBWFaJ8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Fb63wBWFaJ8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-15'),
	(67,34,'Paroles paroles','Dalida & Alain Delon','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/_ifJapuqYiU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/_ifJapuqYiU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-15'),
	(68,33,'Cent mille chansons','Frida Boccara','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/VAdT71n7hII\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/VAdT71n7hII\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-15'),
	(69,32,'Ella elle l’a','France Gall','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/lgHGU8gqz9U\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/lgHGU8gqz9U\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-15'),
	(70,31,'Vous permettez monsieur','Adamo','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/O70E5PYved4\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/O70E5PYved4\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-15'),
	(71,30,'Complainte pour Ste. Cathérine','Kate & Anne McGarrigle','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/wySvN_9CpEo\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/wySvN_9CpEo\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-16'),
	(72,29,'La mer','Charles Trenet','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/fztkUuunI7g\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/fztkUuunI7g\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-16'),
	(73,28,'Pour moi la vie va commençer','Johnny Hallyday','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/YTJoJRTb0L8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/YTJoJRTb0L8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-16'),
	(74,27,'La montagne','Jean Ferrat','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/tkI5wGVjfX8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/tkI5wGVjfX8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-16'),
	(75,26,'Moi… Lolita','Alizée','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/AWU8vI96-AI\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/AWU8vI96-AI\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-17'),
	(76,25,'Casser la voix (live)','Patrick Bruel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Il8r6Ev-zm8\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Il8r6Ev-zm8\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-17'),
	(77,24,'Le plat pays','Jacques Brel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/seMFkItmGFs\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/seMFkItmGFs\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-17'),
	(78,23,'Ça plane pour moi','Plastic Bertrand','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/xTo79sPCVXA\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/xTo79sPCVXA\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-17'),
	(79,22,'Hélène','Julien Clerc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/bagWWB-35oI\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/bagWWB-35oI\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-17'),
	(80,21,'Amsterdam','Jacques Brel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/bkC7WCpJfYY\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/bkC7WCpJfYY\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-18'),
	(81,20,'Poupée de cire, poupée de son','France Gall','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/rRva0YOVtcI\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/rRva0YOVtcI\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-18'),
	(82,19,'Buenas noches mi amor','Dalida','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/iDvyMUcu3qo\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/iDvyMUcu3qo\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-18'),
	(83,18,'Le printemps','Michel Fugain','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/HClfgTGiHDs\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/HClfgTGiHDs\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-19'),
	(84,17,'Je t’aime… moi non plus','Serge Gainsbourg & Jane Birkin','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/k3Fa4lOQfbA\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/k3Fa4lOQfbA\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-19'),
	(85,16,'Après toi','Vicky Leandros','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/6P1paFElB24\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/6P1paFElB24\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-19'),
	(86,15,'This melody','Julien Clerc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/N0ccL5qS7Ic\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/N0ccL5qS7Ic\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-20'),
	(87,14,'Je veux','Zaz','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Tm88QAI8I5A\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Tm88QAI8I5A\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-20'),
	(88,13,'Laat me/Vivre','Alderliefste & Liesbeth List & Ramses Shaffy','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Ih5i8lEpaH0\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Ih5i8lEpaH0\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-20'),
	(89,12,'La bicyclette','Yves Montand','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/eoHjQs6C4UY\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/eoHjQs6C4UY\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-21'),
	(90,11,'Pour un flirt','Michel Delpech','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/yrn0MsKAWDU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/yrn0MsKAWDU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-21'),
	(91,10,'Les lacs du Connemara','Michel Sardou','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/l11GyqVu_-o\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/l11GyqVu_-o\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-21'),
	(92,9,'Aicha','Khaled','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/RvK19xgAxSU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/RvK19xgAxSU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-22'),
	(93,8,'Tous les garçons et les filles','Françoise Hardy','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/0aLoezucIzk\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/0aLoezucIzk\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-22'),
	(94,7,'La ballade des gens heureux','Gérard Lenorman','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/Wzkz9IABhPk\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/Wzkz9IABhPk\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-22'),
	(95,6,'Ne me quitte pas','Jacques Brel','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/i2wmKcBm4Ik\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/i2wmKcBm4Ik\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-23'),
	(96,5,'Non je ne regrette rien','Edith Piaf','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/fFtGfyruroU\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/fFtGfyruroU\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-23'),
	(97,4,'Non non rien n’a changé','Les Poppys','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/V9Po8lSIKww\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/V9Po8lSIKww\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-23'),
	(98,3,'Il est cinq heures Paris s’éveille','Jacques Dutronc','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/-G4EQjFUZOc\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/-G4EQjFUZOc\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-24'),
	(99,2,'Une belle histoire','Michel Fugain','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RPZTZaGtjHs\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/RPZTZaGtjHs\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-24'),
	(100,1,'Nathalie','Gilbert Bécaud','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','<iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/TilQ8BIHisw\" frameborder=\"0\" allowfullscreen></iframe>','<iframe width=\"210\" height=\"140\" src=\"https://www.youtube.com/embed/TilQ8BIHisw\" frameborder=\"0\" allowfullscreen></iframe>','2015-12-24');

/*!40000 ALTER TABLE `topsongs` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
